version: '3.7'

services:
    php-apache:
        image: egghdz/docker-php-apache:latest
        ports:
            - 80:80
        volumes:
            - ./public:/var/www/html
            - .:/var/www
            # Use a named volume instead of the mounted host folder to prevent potential `npm install` issues.
            - node_modules:/var/www/node_modules
        depends_on:
            - mariadb
        command: >
            bash -c ". ~/.bashrc
            && cd /var/www
            && npm install
            && npm run dev
            && php artisan migrate:refresh --seed
            && php artisan config:cache
            && php artisan route:cache
            && apache2-foreground"

    mariadb:
        image: mariadb:latest
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "UTC"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: 'mariadb'
            PMA_USER: 'egghdz_user'
            PMA_PASSWORD: 'egghdzpassword'
        restart: always
        ports:
            - 81:80
        volumes:
            - /sessions
        depends_on:
            - mariadb

volumes:
    mariadb:
    node_modules:
